version: '3.1'
services:
  mongo:
      container_name: mongo
      image: mongo
      restart: always
      ports:
        - "27017:27017"

  mongo-express:
      image: mongo-express
      restart: always
      ports:
        - 8081:8081
      depends_on:
        - mongo
      
  webapi-server:
    container_name: webapi
    build: .
    restart: always
    ports:
      - "5000:80"
      - "44348:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    
    depends_on:
        - mongo
      


    
    
    